version: '3.11'

services:
  web:
    build: .
    container_name: ${SERVICE_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["/bin/sh", "-c", "./scripts/run.sh"]
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"

volumes:
  db_data:
