version: '3.8'

services:
  web:
    build: .
    container_name: ${SERVICE_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["/bin/sh", "-c", "./scripts/run.sh"]
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - web
    restart: always

volumes:
  db_data:
