# Generated by Django 5.1.4 on 2024-12-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_productgallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="media/banner/", verbose_name="Banner"),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                upload_to="media/products/", verbose_name="Gallery"
            ),
        ),
    ]
